---
# tasks file for bareos

- name: Include assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: Add repository (rpm)
  ansible.builtin.yum_repository:
    name: "{{ item.name }}"
    description: "{{ item.description }}"
    baseurl: "{{ item.baseurl }}"
    gpgcheck: yes
    gpgkey: "{{ item.gpgkey }}"
  loop: "{{ bareos_repositories }}"
  loop_control:
    label: "{{ item.name }}"
  when:
    - ansible_pkg_mgr in [ "dnf", "yum" ]

- name: Install bareos packages
  ansible.builtin.package:
    name: "{{ bareos_packages }}"
  notify:
    - Setup database

- name: Start service {{ bareos_service }}
  ansible.builtin.service:
    name: "{{ bareos_service }}"
    state: started
    enabled: yes
