---
# handlers file for bareos

- name: Setup database
  ansible.builtin.command:
    cmd: "{{ item }}"
  become_user: postgres
  become: yes
  loop: "{{ bareos_catalogs }}"
  when:
    - bareos_role == "dir"
