---
- name: Converge
  hosts: all
  become: yes
  gather_facts: yes

  # Bareos has three types of roles: fd (File Daemon), sd (Storage Daemon), and dir (Director).
  # We want to test all three roles, so we need to run the role three times, each time with
  # a different value for the variable bareos_role.
  roles:
    - role: ansible-role-bareos
    - role: ansible-role-bareos
      bareos_role: sd
    - role: ansible-role-bareos
      bareos_role: dir
