---
- name: Prepare
  hosts: all
  become: yes
  gather_facts: no

  # We are going to install all components on one hosts.
  # This is not what is typically done, but works for testing.

  roles:
    - role: robertdebock.bootstrap
    # The roles buildtools, python_pip and postgres are required for the `bareos_role`: "dir".
    # bareos-dir needs to connect to a database.
    - role: robertdebock.buildtools
    - role: robertdebock.python_pip
    - role: robertdebock.postgres
    # The roles core_dependencies and postfix are  required for the `bareos_role`: "dir".
    # bareos-dir needs to send emails.
    - role: robertdebock.core_dependencies
    - role: robertdebock.postfix
